name: TradingApp CI/CD

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        # For now -DskipTests
        run: mvn -B package --file pom.xml -DskipTests

      - name: Run Unit Tests
        run: mvn test
        # For now

        continue-on-error: true

      - name: Run Integration Tests
        run: mvn failsafe:integration-test
        # For now
        continue-on-error: true

      - name: Generate JaCoCo Coverage Report
        run: mvn jacoco:report

      - name: Generate JavaDocs
        run: mvn javadoc:javadoc

      - name: Upload JaCoCo Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/

      - name: Upload JavaDocs
        uses: actions/upload-artifact@v4
        with:
          name: javadocs
          path: target/site/apidocs/

      - name: Deploying reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/site
